# Site settings
# This is where the essential settings of the site are defined.
# Any other data or information is defined in the _data/ folder.
# Any modification on this file requires building again (via jekyll build or jekyll serve).

# SEO-related fields
title: Scientific Research and Development Group
description: >-
  Developing novel approaches.
author: Mohamad Jouni
url: "mhmdjouni.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Custom collections for customly organized and grouped pages
collections:
  pages_navbar:
    output: true
    permalink: /:name/
























# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
